### ISSUE TITLE
Sockets are not closing

### ISSUE THREAD

**Issue by tian2992** [allinurl/gwsocket#15]
https://imgur.com/a/F0caWIT
Running as 
```
app@server:~$ ~/bin/gwsocket -p 6547 --access-log=~/aclogz --ssl-key=~/sslz/privkey1.pem --ssl-cert=~/sslz/fullchain1.pem --pipeout=~/timelogs/sock
```

**Comment by allinurl** [comment]
Thanks for reporting this. Which version of gwsocket are you running? Also, could you please run:

    watch -n1 'netstat -np | grep -i gwsocket'

and check if they are being closed with and without `--ssl*`. Thanks.

**Comment by tian2992** [comment]
Running 0.3 built from source 4f4dc79175b2dfc1654fff7d5a523bcdf75dfd8e . 

there are a bunch of open sockets. Cannot try without ssl as it is moderately sensitive data being sent.

**Comment by allinurl** [comment]
[v0.4](https://gwsocket.io/) is out. Multiple changes were added upstream that may have addressed this issue.

Closing this for now, feel free to reopen it as needed. Thank you!
