### ISSUE TITLE
Getting HTTP ERROR 400

### ISSUE THREAD

**Issue by shashank-ssriva** [allinurl/gwsocket#19]
Whenever I try to access gwsocket web UI, I receive HTTP ERROR 400. I am using ``gwsocket-0.3``.

Below is the message that appears on the browser.

```
This page isn’t working If the problem continues, contact the site owner.
HTTP ERROR 400
```

**Comment by allinurl** [comment]
Can I ask what do you mean with gwsocket Web UI? Thanks

**Comment by shashank-ssriva** [comment]
> Can I ask what do you mean with gwsocket Web UI? Thanks

Ok, sorry. I should have described it more. When I try to access ``gwsocket`` in a browser by pointing to the default port, I get this error.

**Comment by allinurl** [comment]
Can you please post the exact command that you are running so I can try to reproduce this from my end? Thanks.

**Comment by willkof1** [comment]
I have the same problem
gwsocket --access-log=/var/log/syslog or /var/log/apache2/access.log and yes this is the path of my log.

**Comment by allinurl** [comment]
I can't reproduce this on my end. Would be able to debug this through gdb?

**Comment by nickosh** [comment]
Hello. Gwsocket looks great but same problem here. System is WSL1 with Ubuntu 18.04.3 LTS.

I run gwsocket like this: gwsocket --access-log=/tmp/access.log --port=8888

And get a ERROR 400 no matter what I try in browser (like localhost:8888 or localhost:8888/terminal)

In access.log:

> 127.0.0.1 - - [03/Oct/2020:03:40:44 +0300] "GET / HTTP/1.1" 400 551 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:40:44 +0300] "GET / HTTP/1.1" 200 551 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:40:52 +0300] "GET /terminal.html HTTP/1.1" 400 650 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:40:52 +0300] "GET /terminal.html HTTP/1.1" 200 650 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:41:37 +0300] "GET /terminal.html HTTP/1.1" 400 564 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:41:37 +0300] "GET /terminal.html HTTP/1.1" 200 564 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:41:39 +0300] "GET / HTTP/1.1" 400 637 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:41:39 +0300] "GET / HTTP/1.1" 200 637 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:41:42 +0300] "GET / HTTP/1.1" 400 663 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:41:42 +0300] "GET / HTTP/1.1" 200 663 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:42:17 +0300] "GET / HTTP/1.1" 400 551 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0
127.0.0.1 - - [03/Oct/2020:03:42:17 +0300] "GET / HTTP/1.1" 200 551 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 0

Any solution?

**Comment by allinurl** [comment]
I need to apply the [fix](https://github.com/allinurl/goaccess/issues/969) from goaccess ([commit](https://github.com/allinurl/goaccess/commit/9b1a90924c550d61e2e3fc7657adff9a0849825b)). Are you able to post the request headers?

**Comment by allinurl** [comment]
Pushed a fix for this. Please feel free to build from [**development**](https://github.com/allinurl/gwsocket#build-from-github) and let me know if that addresses the issue on your end. Thanks.

**Comment by nickosh** [comment]
Sorry, too late but still, headers:

> GET / HTTP/1.1
> Host: localhost:8888
> Connection: keep-alive
> Cache-Control: max-age=0
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
> Sec-Fetch-Site: cross-site
> Sec-Fetch-Mode: navigate
> Sec-Fetch-User: ?1
> Sec-Fetch-Dest: document
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en-US,en;q=0.9

Thanks. I try to build version with fix.

**Comment by nickosh** [comment]
Build version with fix but still same error. Headers:

> Request URL: http://localhost:8888/
> Request Method: GET
> Status Code: 400 Invalid Request
> Remote Address: 127.0.0.1:8888
> Referrer Policy: no-referrer-when-downgrade
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en-US,en;q=0.9
> Connection: keep-alive
> Cookie: Pycharm-c28352c8=f799eca8-17b5-4844-9bbe-bcc6aeab4400; Pycharm-cee2178c=34859c46-54e2-4e86-9f5e-f5b22f0df20a
> Host: localhost:8888
> Sec-Fetch-Dest: document
> Sec-Fetch-Mode: navigate
> Sec-Fetch-Site: none
> Sec-Fetch-User: ?1
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

**Comment by franciscopaniskaseker** [comment]
Same problem here.

I installed from git repository.

```bash
root@h:~/gwsocket# gwsocket --version
GWSocket 0.4
```

the command:
```bash
root@h:~/gwsocket# gwsocket --access-log=/home/linuxrecipe/web/linux.recipes/logs/linux.recipes.log
```

I got 400 http error when i try to access ip:7890.
<img width="1341" alt="Captura de Tela 2022-02-15 às 16 28 00" src="https://user-images.githubusercontent.com/8779476/154134712-79972915-49f6-41bc-b9a1-9b0473fec4fe.png">

**Comment by allinurl** [comment]
@franciscopaniskaseker Can you please share how you are connecting the client to the WS? also, are you using https or http when opening the client side?

**Comment by franciscopaniskaseker** [comment]
I am trying to access using http://ip:7890 or http://dns:7890 thorugh last stable google chrome (from mac). The DNS does not has any kind of proxy. last stable firefox and safari got same behavior.

The command is the same:
```bash
root@h:~# gwsocket --access-log=/home/linuxrecipe/web/linux.recipes/logs/linux.recipes.log
```

let me know how can I help to troubleshoot this. The telnet tool can open the conversation with 7890 tcp port.

**Comment by allinurl** [comment]
@franciscopaniskaseker How about the index page that you are opening when typing http://ip:7890/ ? you'll need to connect via JS through the Web Socket API https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by franciscopaniskaseker** [comment]
The error is the index page. I though that was enough to get access of the log.
I was testing because I want to export goaccess report through gwsocket like this live demo: https://rt.goaccess.io/?20220201082423

**Comment by allinurl** [comment]
@franciscopaniskaseker no worries. As far as exporting the data from the report, goaccess should already handle this for you. gwsocket would be great for any other data you want to handle from the client to the server or vice-versa. Let me know if you have any additional questions, happy to help :)

**Comment by franciscopaniskaseker** [comment]
thank you for your time and patience!
