### ISSUE TITLE
Cannot write to wspipein.fifo

### ISSUE THREAD

**Issue by The2beats4hits** [allinurl/gwsocket#21]
Commands provided on the manual page for sending data doesn't work for me. 
E.g. 
sudo tail -f /var/log/nginx/access.log > /tmp/wspipein.fifo (NO RESULTS)
also tried python code attached there - same result. Just empty fifo file.
Tried on Mac OS and Ubuntu 18.04.

wspipeout is also empty

What may cause problem? Running under ngrok in pair with nginx, clients - Android

**Comment by allinurl** [comment]
Did you solve the issue? Thanks

**Comment by The2beats4hits** [comment]
Sorry for opening, unchecked that my code was running on python3, and there was exception about writing bytes instead of string. Fixed now. Thanks
