### ISSUE TITLE
Listening on IPv6.

### ISSUE THREAD

**Issue by MrSorcus** [allinurl/gwsocket#24]
gwsocket won't listen on IPv6.
```
gwsocket --addr "[::]" --echo-mode
gwsocket --addr :: --echo-mode
```
No result in `ss --ipv6 --tcp --all`

**Comment by allinurl** [comment]
Thanks for reporting this. It looks like I missed setting this option through `ws_set_config_host`. I'll have a fix for this.

**Comment by allinurl** [comment]
This should be fixed. Please build from [development](https://github.com/allinurl/gwsocket#build-from-github) and let me know if that solves the issue on your end. Thanks.
