### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by gbrantzos** [allinurl/gwsocket#3]
I try to access gwsocket with the url http://ip-address:7890/terminal.html, but I keep getting 400 invlid request. Am I trying the correct address?

Thanks

**Comment by allinurl** [comment]
The web-socket server runs by default on port `7890`. The html file can run on any port or even opening the file from your browser, e.g., `file:///home/user/terminal.html`.

Please take a look at [**this**](https://github.com/allinurl/gwsocket/issues/2#issuecomment-218225160), it might be the same issue you are having.

**Comment by gbrantzos** [comment]
Thanks for your prompt answer!
I can see the output now. Do you have any idea about handling escape 
characters from html code?


Thanks for your time.

g.brantzos@gmail.com


Please consider your environmental responsibility before printing this 
e-mail!



------ Original Message ------

**Comment by allinurl** [comment]
Good question. If you are outputting simple ansi stuff, you can try **[ansi_up](https://github.com/drudru/ansi_up)**, just need to include one js file. 

For more complex terminal outputs and even the ability to send commands to the actual terminal from your browser, your can use [hterm](https://github.com/macton/hterm). Take a look at the code behind the [sample file ](http://gwsocket.io/hterm/)I used for a full-blown terminal output. It's only one `JS` file

**Comment by gbrantzos** [comment]
Looks really nice and promising.
Thanks alot!!!


------ Original Message ------

**Comment by allinurl** [comment]
No problem. Closing this, feel free to reopen it if needed.
