### ISSUE TITLE
Is webshell considered to be integrated into the project?

### ISSUE THREAD

**Issue by wnjustdoit** [allinurl/gwsocket#32]
Is webshell considered to be integrated into the project? Or can you recommend some useful webshell tools? (Only used for LAN, such as in company)

**Comment by allinurl** [comment]
Sorry, not sure I follow your question. Are you referring to having a terminal via web? If it is, please take a look at [**this**](https://github.com/allinurl/gwsocket/issues/31#issuecomment-643039071) post

**Comment by wnjustdoit** [comment]
Yes, web ssh, or terminal on the browser. I think I'd got this function through others ways. Thank you.
