### ISSUE TITLE
" unrecognized option `--ssl-cert' "

### ISSUE THREAD

**Issue by crotel** [allinurl/gwsocket#35]
sys: macOS Catalina[10.15.6]

> openssl version: LibreSSL 2.8.3

follow =>
```
$ wget http://tar.gwsocket.io/gwsocket-0.3.tar.gz
$ tar -xzvf gwsocket-0.3.tar.gz
$ cd gwsocket-0.3/
$ ./configure --with-openssl=/usr/bin/openssl/
$ make
# make install
```

command
' gwsocket --ssl-cert=/path/to/my/ssl/cert --ssl-key=/path/to/my/ssl/key '
or 
' gwsocket --ssl-cert /path/to/my/ssl/cert --ssl-key /path/to/my/ssl/key '

then failed with 
" unrecognized option `--ssl-cert' "

any thing wrong?

PS: here is my config.log
[config.log](https://github.com/allinurl/gwsocket/files/5345272/config.log)

**Comment by allinurl** [comment]
Does it work without specifying the path? e.g.,

    ./configure --with-openssl

**Comment by imatasic** [comment]
I have replicated this on Ubuntu 20, 

when not using the path, the configure returns:
```
  Linker flags   : -lssl
  TLS/SSL        : yes
```

when not using the path (or using `--with-openssl=yes` ), the configure returns:

```
...
  Linker flags   : -lssl
  TLS/SSL        : yes
...
```

When using the path, it returns:

```
...
  Linker flags   :
  TLS/SSL        : /usr/bin/openssl
...
```

So I guess using the path is the wrong argument for that flag.

---

I stumbled here hopping that using the path would solve my issue, as I get the OpenSSL error when running make.

**Comment by allinurl** [comment]
Referencing #36

**Comment by allinurl** [comment]
Any updates? Thanks

**Comment by guest271314** [comment]
What is the fix for this?

**Comment by guest271314** [comment]
I think one issue is libssl-dev is a dependency. Installing openssl alone does not achieve the expected result.

**Comment by allinurl** [comment]
That's correct, since you are building from source, you need `libssl-dev`.

**Comment by allinurl** [comment]
Also, make sure to run `make distclean` + `autoreconf -fiv` and then `./configure --with-openssl` + `make` after installing `libssl-dev`.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by guest271314** [comment]
> That's correct, since you are building from source, you need `libssl-dev`

It would be helpful if that information was in the README. Installing `openssl` alone still results in errors.

> Also, make sure to run `make distclean`

What does `distclean` do?

BTW, thanks for this library. Finally got it working with https://github.com/ratboy666/qjs-ws.

**Comment by allinurl** [comment]
`distclean` will clean files that configure generated.

Glad it's working. [Stay tuned](https://twitter.com/goaccess) as there are some fixes that I need to merge from goaccess' branch into gwsocket.

**Comment by guest271314** [comment]
I don't visit Twitter much after somebody over there banned me for the nth time and won't respond to my inqueries about my data. I'll check back here periodically. 

One question I do have is if it possible to send a PING from the browser? 

Over here https://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser this approach is suggested https://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser#comment125597153_10586583. 

However I have no idea how or if it is even possible to do that using the `wrtiable` side `WebSocketStream` https://github.com/ricea/websocketstream-explainer. I can formally ask the question in a new issue if that is necessary.

**Comment by allinurl** [comment]
@guest271314 Take a look at what goaccess does [**here**](https://github.com/allinurl/goaccess/blob/master/resources/js/app.js#L114), may help with the ping.

**Comment by guest271314** [comment]
@allinurl I deleted my comment re PING after re-reading this

> [**Non-goals in the first version**](https://github.com/ricea/websocketstream-explainer#non-goals-in-the-first-version)
> Exposing WebSocket [pings and pongs](https://tools.ietf.org/html/rfc6455#page-37) to JavaScript.

Right now I am still working on using gwsocket in QuickJS. Unfortunately the machine froze yesterday streaming real-time audio.
