### ISSUE TITLE
TAR Download broken

### ISSUE THREAD

**Issue by KorribanMaster** [allinurl/gwsocket#39]
http://tar.gwsocket.io/gwsocket-0.3.tar.gz is not reachable

**Comment by allinurl** [comment]
Thanks for the heads up. It's strange, it's up from my end. Can you please try the https version?

https://tar.gwsocket.io/gwsocket-0.3.tar.gz

**Comment by KorribanMaster** [comment]
Hey I checked the https version and http version today and both work now.
Issue will be closed
