### ISSUE TITLE
-Wno-missing-field-initializers on SPARC machine

### ISSUE THREAD

**Issue by crisGuada** [allinurl/gwsocket#40]
Hello
I am trying to compile the gwsocket on a SPARC machine with solaris and it gives me this error while doing the makefile.
What can be?
(I clarify, I am not an expert in unix)

**Comment by allinurl** [comment]
This may be hard to debug as I don't have access to a SPARC machine. Still, could you please post the errors that you are getting?

**Comment by crisGuada** [comment]
this is the error:
depbase=`echo src/base64.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src     -O2 -Wno-long-long -Wall -W -Wnested-externs  -Wformat=2 -Wmissing-prototypes  -Wstrict-prototypes -Wmissing-declarations  -Wwrite-strings -Wshadow -Wpointer-arith  -Wsign-compare -Wredundant-decls  -Wbad-function-cast -Winline -Wcast-align -Wextra  -Wdeclaration-after-statement  -Wno-missing-field-initializers  -MT src/base64.o -MD -MP -MF $depbase.Tpo -c -o src/base64.o src/base64.c &&\
mv -f $depbase.Tpo $depbase.Po
cc1: error: unrecognized command line option "-Wno-missing-field-initializers"
*** Error code 1
make: Fatal error: Command failed for target `src/base64.o'

**Comment by allinurl** [comment]
Can you please try removing the `-Wno-missing-field-initializers` from the [Makefile.am](https://github.com/allinurl/gwsocket/blob/master/Makefile.am#L40)? and building again as described [here](https://github.com/allinurl/gwsocket#installation).

**Comment by allinurl** [comment]
Any updates on this? Thanks

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
