### ISSUE TITLE
Help with FIFO Error. Bad address

### ISSUE THREAD

**Issue by daddyfix** [allinurl/gwsocket#41]
I built v 0.4.0 on Buster (Raspberry Pi 4 Model B Rev 1.1)

But I get this error when trying to pipein fifo. Any help would be appreciated

```
$ gwsocket -p 8080 --pipein=/tmp/websocket/wspipein.fifo
 
Fatal error has occurred
Error occured at: src/websocket.c - ws_setfifo - 2292
Unable to set fifo: Bad address.
```

### websocket.c - Line 2279+
```

/* Create named pipe (FIFO) with the given pipe name.
 *
 * On error, 1 is returned.
 * On success, 0 is returned. */
int
ws_setfifo (const char *pipename) {
  struct stat fistat;
  const char *f = pipename;

  if (access (f, F_OK) == 0)
    return 0;

  if (mkfifo (f, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH) < 0)
    FATAL ("Unable to set fifo: %s.", strerror (errno));
  if (stat (f, &fistat) < 0)
    FATAL ("Unable to stat fifo: %s.", strerror (errno));
  if (!S_ISFIFO (fistat.st_mode))
    FATAL ("pipe is not a fifo: %s.", strerror (errno));

  return 0;
}
```

**Comment by electronics-lis** [comment]
Hi, I've the same problem and tried chmod 757 and 777 and 10777  /tmp/ with any effects. Always the same error. I'm using raspberry 4. My best lelis

**Comment by lelisele** [comment]
My gwsocket worked well with Rpi 2. The option as _--pipein=<path/file>_gives the same error but mkfifo in my C program works well even for /tmp/ folder. Anyway, gwsocket is always stopped (bad address) and impossible to use. The best solution could be perhaps to comment this lines and recompile websocket.c but .......Any way I have to switch to Ajax, exec() in PHP and C brrrrrr. My Best lelis

**Comment by daddyfix** [comment]
I found out that version 0.3.0 works as expected I'm using that version for
now and I will probably have to comment out the mkfifo check in version
0.4.0. thanks for your help I'm going to keep working on it and let you
know what happens

**Comment by allinurl** [comment]
Could you please try passing `--pipeout=<path>`. e.g.,

    gwsocket --pipein=/tmp/wspipein.fifo --pipeout=/tmp/wspipeout.fifo

Seems like I'll need to address the default path. Let me know how it goes. Thanks

**Comment by allinurl** [comment]
By the way, you can also try piping data in. e.g., 

    tail -F /var/log/apache2/access.log | gwsocket --std --port 7890

**Comment by lelisele** [comment]
Thanks allinurl for your help. These options gives the same error (bad address) with "my" folder. Do I need to test with /tmp/?. I've just finished to implement my C program to control serial UART via USB0 and would like to send some data from my web page directedly to C interface and external RealTime DSP target. That worked well in Rpi2 and now not really. I've tried mkfifo with address 0777 and was able to generate fifo in /tmp/

**Comment by allinurl** [comment]
Pushed an update. It should solve the issue. There's no need for setting `--pipein=/tmp/wspipein.fifo` `--pipeout=/tmp/wspipeout.fifo`  as it will use those paths as default.

Please rebase from origin and let me know how it goes.

**Comment by daddyfix** [comment]
That's great.. will do

**Comment by lelisele** [comment]
A lot of thanks allinurl !!!!! For me it works. Bye, bye PHP and its exec() brrrr. lelisele

**Comment by daddyfix** [comment]
> Pushed an update. It should solve the issue. There's no need for setting `--pipein=/tmp/wspipein.fifo` `--pipeout=/tmp/wspipeout.fifo` as it will use those paths as default.
> 
> Please rebase from origin and let me know how it goes.

After new build this date it works great on Raspberry Pi 4 (buster) Thanks

**Comment by allinurl** [comment]
Great to hear that. Thanks for letting me know!
