### ISSUE TITLE
gwsocket.io: :( Nope, the connection is out. Try again later!

### ISSUE THREAD

**Issue by brlin-tw** [allinurl/gwsocket#44]
Got this error when browsing [[Simple WebSocket Server RFC6455 compliant - GWSocket](https://gwsocket.io/)](https://gwsocket.io/), something seems to be broken?

**Comment by allinurl** [comment]
Thanks for reporting this. Issue should be fixed. Please try again.

**Comment by brlin-tw** [comment]
Yes it is fixed, thanks!
