### ISSUE TITLE
Cant get it to work with openssl

### ISSUE THREAD

**Issue by vaguiners** [allinurl/gwsocket#45]
I get it to work on non-ssl version perfectly

but when i compile with --with-openssl, it just don't work

it fails instantly without message
"WebSocket connection to 'wss:///' failed: "

Log shows the connection attempt
```
my IP - - [26/Aug/2022:21:14:30 +0000] "(null) - (null)" 400 0 "-" "-" 0
my IP - - [26/Aug/2022:21:14:30 +0000] "(null) - (null)" 200 0 "-" "-" 0
7 8 0
CLOSE
```
started correctly with cert and key.

**Comment by vaguiners** [comment]
my certs was wrong sorry

nice program

**Comment by allinurl** [comment]
Awesome, thanks for sharing that and glad you got it to work. I'll be pushing an update on this with the latest changes/fixes. Stay tuned.

**Comment by vaguiners** [comment]
> Awesome, thanks for sharing that and glad you got it to work. I'll be pushing an update on this with the latest changes/fixes. Stay tuned.

how can i get it to work with cloudflare? im getting ip from header "remote_addr" but i need from CF-Connecting-IP

**Comment by allinurl** [comment]
gwsocket will just forward the data you pass to either the server or the client. What are you trying to do?

**Comment by vaguiners** [comment]
> gwsocket will just forward the data you pass to either the server or the client. What are you trying to do?

cloudflare proxies the connection but it passes the real user ip on header on "CF_CONNECTING_IP"

**Comment by allinurl** [comment]
what are you trying to do with the IP? are you looking to analyze the logs? then please use goaccess instead of gwsocket.

**Comment by vaguiners** [comment]
i figured out how to fix
