### ISSUE TITLE
No data when starting to write before first client is connected

### ISSUE THREAD

**Issue by pmf** [allinurl/gwsocket#51]
I have the problem(?) that when I start piping into `/tmp/wspipein.fifo` after starting `gwsocket`, but before a client is connected, I never get data (i.e. not even data that is piped into `/tmp/wspipein.fifo` after the client has connected). Otherwise (if I first cause a client to connect, and then start piping), everything works.

Is this the expected behavior (if not, it might be something related to my custom CMake based build and related config that I have to look into my side)?

**Comment by allinurl** [comment]
Excellent question! It should allow you to establish a connection by either opening the client or starting the server first; it shouldn't pose any issues. That's how it operates on the gwsocket.io site. Have you built it with the `--enable-debug` option?

**Comment by pmf** [comment]
Hm, can no longer reproduce this.
