### ISSUE TITLE
When disconnecting from fifo CPU usage goes very high

### ISSUE THREAD

**Issue by tomski-spqr** [allinurl/gwsocket#53]
1. Started gwsocket with:
`./gwsocket --pipein=in.fifo --pipeout=out.fifo
`
2. Open a console and do:
`cat out.fifo
`
3. Connect with the test html application to the websocket and send an "Hello world" message.
--> The message is printed on the console as expected.

4. Break `(CTRL-C)` the cat command.

As soon as I stop the cat command (and thus disconnect from the pipe), the CPU usage of gwsocket jumps to almost 100%

**Comment by allinurl** [comment]
Thanks for the heads-up. It seems like it might be related to the `select()` call. Could you please run it with `strace` and let me know which call is consuming all the CPU?

**Comment by tomski-spqr** [comment]
On holiday for a while, hence the delay :-)

`poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=0}], 5, -1) = 1 ([{fd=8, revents=POLLERR}])`

Seems fd=8 (I guess this the file descriptor from out.fifo) causes a POLLERR

**Comment by tomski-spqr** [comment]
`--- src/websocket.c.original	2024-08-11 13:37:58.990833419 +0200
+++ src/websocket.c	2024-08-11 13:40:50.389018470 +0200
@@ -2866,9 +2866,15 @@
         LOG (("Got POLLHUP %d\n", pfd->fd));
       if (pfd->revents & POLLNVAL)
         LOG (("Got POLLNVAL %d\n", pfd->fd));
-      if (pfd->revents & POLLERR)
+      if (pfd->revents & POLLERR) {
         LOG (("Got POLLERR %d\n", pfd->fd));
-
+        if (pfd->fd == server->pipeout->fd) {
+		  LOG (("Reopen pipeout\n"));
+		  ws_close (pfd->fd);
+		  ws_openfifo_out (server->pipeout);
+	    }
+      }
+      
       /* handle self-pipe trick */
       if (pfd->fd == server->self_pipe[0]) {
         if (pfd->revents & POLLIN) {
`

Fixed with the above patch (re-opening pipeout)

**Comment by tomski-spqr** [comment]
Fixed with attached patch.
[2024-08-11-fix-high-cpu.patch.gz](https://github.com/user-attachments/files/16573548/2024-08-11-fix-high-cpu.patch.gz)

**Comment by allinurl** [comment]
I completely overlooked this update. Thanks for submitting the patch! I’ve pushed it upstream, and it will be included in the next release.
