### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by wrfeewrtgaqwfrwaq** [allinurl/gwsocket#54]
Really great work, I must say! I've been diging into the code a little bit to customize it to my needs and I think the following code is slightly redundant. There's no benefit to calling `ws_set_config_stdin` twice so the top if could just be removed.
```
  if (gsconfig.use_stdin && gsconfig.use_stdout) {
    ws_set_config_stdin (1);
    ws_set_config_stdout (1);
  }
  if (gsconfig.use_stdin)
    ws_set_config_stdin (1);
  if (gsconfig.use_stdout)
    ws_set_config_stdout (1);
  if (gsconfig.unix_socket)
```

**Comment by allinurl** [comment]
Thank you for pointing out the redundant code! I've pushed a change to address it. I really appreciate it!
