### ISSUE TITLE
Allow to read from gwsocket’s stdin with (unnamed) pipe

### ISSUE THREAD

**Issue by jirutka** [allinurl/gwsocket#7]
It’d be great to be able to do simply `tail -f /var/log/nginx/access.log | gwsocket`.

Currently it’s possible to read user input from stdin and/or write to stdout using `gwsocket --pipein=/dev/stdin --pipeout=/dev/stdout`, but this doesn’t work with `|`.

**Comment by allinurl** [comment]
I'll look into this, shouldn't be too bad adding stdin to the fd set. Thanks for pointing this out!
